import "./globals.css";
import "@/styles/colors.css"

export const metadata = {
  title: "Amrit Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
